export default {
  responseId: 'afd2d952-65ec-4c42-9c09-55c9a2730080',
  data: [
    {
      id: '6698fa9364527c728f0d81ce',
      category: 'promo',
      gaCategory: 'promo_birthday_change_n_win1',
      title: 'Slider Promo Birthday Change & Win (13.06-24.07)',
      description:
        '<div class="gap-xs color-text-alt"><div class="banner-caption">Birthday Change &amp; Win Promotion</div><div class="banner-title"><span class="variable-box">{amount}</span>&nbsp;<br>+ 1 000 FS each!</div></div>',
      position: 7,
      button: {
        name: 'Join now',
        url: '/actions/birthday_change_n_win',
      },
      link: null,
      bgColor: 'linear-gradient(to right, #4c0b53 0%,#7b0880 50%,#e100e1 100%)',
      desktop: '',
      mobile: '',
      localisation: {
        variables: {
          amount: {
            AUD: '20 550 AUD',
            NZD: '20 550 NZD',
            CAD: '20 550 CAD',
            EUR: '12 700 EUR',
            USD: '12 700 USD',
            INR: '1 270 000 INR',
            BRL: '25 400 BRL',
          },
        },
      },
      types: ['slider'],
      compostelaImagePath: '/svc/img/i/Temp/banners/Small_New_Change___Win_png.png',
      status: 'active',
      startAt: '2024-07-18T14:17:00+00:00',
      endAt: '2024-07-24T14:59:00+00:00',
      tags: ['mainHome', 'mainCasino'],
    },
    {
      id: '66992026c47756728d0c6ec6',
      category: 'promo',
      gaCategory: 'tournament_live_fight1',
      title: 'Slider Live Fight (18.07.24-24.07.24)',
      description:
        '<div class="gap-xs color-text-alt"><div class="banner-caption">Live Fight - Tournament</div><div class="banner-title">Be one of the 15 winners!</div></div>',
      position: 9,
      button: {
        name: 'Tell me more',
        url: '/tournaments/2024-29Live-Fight',
      },
      link: null,
      bgColor: 'linear-gradient(to right, #470a58 0%,#690680 50%,#ac01c9 100%)',
      desktop: '',
      mobile: '',
      localisation: {
        variables: [],
      },
      types: ['slider'],
      compostelaImagePath: '/svc/img/i/Temp/banners/Live__1__png.png',
      status: 'active',
      startAt: '2024-07-18T16:55:00+00:00',
      endAt: '2024-07-24T16:55:00+00:00',
      tags: ['mainLive'],
    },
    {
      id: '66996805d00d39ba3b073aca',
      category: 'promo',
      gaCategory: 'Vip_Cashback1',
      title: 'Slider Vip Cashback',
      description:
        '<div class="gap-xs color-text-alt"><div class="banner-caption">No-deposit cashback</div><div class="banner-title">Up to 15% cashback every week</div></div>',
      position: 11,
      button: {
        name: 'Tell me more',
        url: '/vip#cashback',
      },
      link: null,
      bgColor: 'linear-gradient(to right, #2c0a5b 0%,#3b0b7d 50%,#6c01f3 100%)',
      desktop: '',
      mobile: '',
      localisation: {
        variables: [],
      },
      types: ['slider'],
      compostelaImagePath: '/svc/img/i/Temp/banners/Cashback_Banner_1140x720_png.png',
      status: 'active',
      startAt: '2024-07-18T22:04:00+00:00',
      endAt: null,
      tags: ['mainHome', 'mainCasino', 'mainLive'],
    },
    {
      id: '66996a10a1ce392d7601dc71',
      category: 'promo',
      gaCategory: 'Wednesday_free_spins1',
      title: 'Slider Wednesday free spins',
      description:
        '<div class="gap-xs color-text-alt"><div class="banner-caption">Wednesday bonus</div><div class="banner-title">Grab up to&nbsp;<br>50 Free Spins</div></div>',
      position: 12,
      button: {
        name: 'Tell me more',
        url: '/bonus#regularBonuses',
      },
      link: null,
      bgColor: 'linear-gradient(to right, #2c0a5b 0%,#3b0b7d 50%,#6c01f3 100%)',
      desktop: '',
      mobile: '',
      localisation: {
        variables: [],
      },
      types: ['slider'],
      compostelaImagePath: '/svc/img/i/Temp/banners/Wednesday_Free_Spins_Banner_1140x720_png.png',
      status: 'active',
      startAt: '2024-07-22T17:39:00+00:00',
      endAt: null,
      tags: ['mainHome', 'mainCasino'],
    },
    {
      id: '66996c780e9de24a5704d0b5',
      category: 'promo',
      gaCategory: 'Sunday_gift1',
      title: 'Slider Sunday gift',
      description:
        '<div class="gap-xs color-text-alt"><div class="banner-caption">Sunday bonus</div><div class="banner-title">Claim up to&nbsp;<br>30% deposit bonus</div></div>',
      position: 13,
      button: {
        name: 'Tell me more',
        url: '/bonus#regularBonuses',
      },
      link: null,
      bgColor: 'linear-gradient(to right, #2c0a5b 0%,#3b0b7d 50%,#6c01f3 100%)',
      desktop: '',
      mobile: '',
      localisation: {
        variables: [],
      },
      types: ['slider'],
      compostelaImagePath: '/svc/img/i/Temp/banners/SundayGift_Banner_1140x720_png.png',
      status: 'active',
      startAt: '2024-07-23T10:45:00+00:00',
      endAt: null,
      tags: ['mainHome', 'mainCasino', 'mainLive'],
    },
    {
      id: '6698fa9364527c728f0d81ce',
      category: 'promo',
      gaCategory: 'promo_birthday_change_n_win1',
      title: 'Slider Promo Birthday Change & Win (13.06-24.07)',
      description:
        '<div class="gap-xs color-text-alt"><div class="banner-caption">Birthday Change &amp; Win Promotion</div><div class="banner-title"><span class="variable-box">{amount}</span>&nbsp;<br>+ 1 000 FS each!</div></div>',
      position: 7,
      button: {
        name: 'Join now',
        url: '/actions/birthday_change_n_win',
      },
      link: null,
      bgColor: 'linear-gradient(to right, #4c0b53 0%,#7b0880 50%,#e100e1 100%)',
      desktop: '',
      mobile: '',
      localisation: {
        variables: {
          amount: {
            AUD: '20 550 AUD',
            NZD: '20 550 NZD',
            CAD: '20 550 CAD',
            EUR: '12 700 EUR',
            USD: '12 700 USD',
            INR: '1 270 000 INR',
            BRL: '25 400 BRL',
          },
        },
      },
      types: ['slider'],
      compostelaImagePath: '/svc/img/i/Temp/banners/Small_New_Change___Win_png.png',
      status: 'active',
      startAt: '2024-07-18T14:17:00+00:00',
      endAt: '2024-07-24T14:59:00+00:00',
      tags: ['mainHome', 'mainCasino'],
    },
    {
      id: '99992026c47756728d0c6ec6',
      category: 'promo',
      gaCategory: 'tournament_live_fight1',
      title: 'Slider Live Fight (18.07.24-24.07.24)',
      description:
        '<div class="gap-xs color-text-alt"><div class="banner-caption">Live Fight - Tournament</div><div class="banner-title">Be one of the 15 winners!</div></div>',
      position: 9,
      button: {
        name: 'Tell me more',
        url: '/tournaments/2024-29Live-Fight',
      },
      link: null,
      bgColor: 'linear-gradient(to right, #470a58 0%,#690680 50%,#ac01c9 100%)',
      desktop: '',
      mobile: '',
      localisation: {
        variables: [],
      },
      types: ['slider'],
      compostelaImagePath: '/svc/img/i/Temp/banners/Live__1__png.png',
      status: 'active',
      startAt: '2024-07-18T16:55:00+00:00',
      endAt: '2024-07-24T16:55:00+00:00',
      tags: ['mainHome', 'mainLive'],
    },
  ],
  error: null,
};
