export default {
  id: '60a4b3ee2cbf0a0ae374d788',
  user_id: '60a4b3ee2cbf0a0ae374d787',
  lastname: null,
  firstname: null,
  middlename: null,
  address: null,
  country: 'UA',
  chosen_country: 'CA',
  gender: null,
  birthday: null,
  birthday_verified: false,
  nick_name: 'a.chistik',
  hash: '34163908f5bb2211c05b13369ce1e3fff062212f',
  emails: [
    {
      email: 'a.chistik@bbq.agency',
      is_primary: true,
      is_verified: true,
    },
  ],
  phones: [],
  registration_contact_type: 'email',
  multi_account: false,
  support_manager_id: null,
  status: 10,
  currency: 'RUB',
  service_achievements: [],
  new_front: null,
  force_new_front: false,
  vipManager: {
    id: '654b29bcd12561d8c0af72a',
    publicName: 'Viktory',
    email: 'Viktory@test.tech',
    whatsapp: 'https://wa.me/0',
    telegram: 'https://t.me/m',
    profilePicture: '',
    gender: 'female',
    phoneNumbers: null,
    dateStart: {
      date: '2024-04-02 16:00:00',
      weekday: 1,
    },
    dateEnd: {
      date: '2024-04-02 00:00:00',
      weekday: 5,
    },
  },
  progressions: {
    static: {
      xp: 0,
      order: 9,
    },
    dynamic: {
      sp: 17813,
      isConfirmed: false,
      isAutoConfirmed: true,
      code: 80,
    },
  },
  registrationDate: '2025-10-01 08:37:29',
};
